### ISSUE TITLE
Claim 14 doesn't affect score

### ISSUE THREAD

**Issue by Wuzzy2** [politicalcompass/politicalcompass.github.io#1]
If you click the radio buttons for claim 14, nothing happens. Is this actually a dud in the original test or is this just a bug?

**Comment by politicalcompass** [comment]
@Wuzzy2 nothing happens in the original test when you change your response for question 14. Since the test authors haven't published any methodology whatsoever, we have no way of knowing whether this was intended by the authors or not.

**Comment by Wuzzy2** [comment]
Haha, nice. It's hilarious they actually included a pointless claim. But yes, this is not your fault then. Thanks for letting me know. :D
